Add inline buttons for !pic cmd instead of !more cmd
alexbft/imouto pull request #10
Opened 2017-12-02 11:23 UTC by goodmind

2017-12-03 15:26 UTC, alexbft requested changes

2017-12-03 15:26 UTC, alexbft commented on plugins/images.coffee
> +search = (txt, rsz = 1, offset = 1) ->
offset = 0?

2017-12-03 15:26 UTC, alexbft commented on plugins/images.coffee
> +                    logger.info 'disable prev button'
logger.debug

2017-12-03 15:26 UTC, alexbft commented on plugins/images.coffee
> +        #if not txt? and msg.match[1].toLowerCase() in ['moar', 'моар', 'more', 'еще', 'ещё']
убери комменты

2017-12-03 15:26 UTC, alexbft commented on plugins/images.coffee
> +                        @search(context.txt, context.picSet.length).then (results) =>
сделай тогда чтобы пока поиск не закончился, next/prev не работали.
Иначе будет race condition

2017-12-03 16:12 UTC, goodmind commented on plugins/images.coffee
> +search = (txt, rsz = 1, offset = 1) ->
Так не работает

2017-12-03 16:12 UTC, goodmind commented on plugins/images.coffee
> +                        @search(context.txt, context.picSet.length).then (results) =>
ето как

2017-12-03 16:15 UTC, alexbft commented on plugins/images.coffee
> +                        @search(context.txt, context.picSet.length).then (results) =>
сначала пишешь isDisabled = true
когда поиск закончился пишешь isDisabled = false
при нажатии кнопки проверяешь если isDisabled то нахуй
ну и локально для контекста да

2017-12-04 18:12 UTC, alexbft approved these changes

2017-12-04 18:13 UTC, merged